import 'package:ball_block_game/block.dart';
import 'package:flutter/material.dart';

class BlockWidget extends StatelessWidget {

  BlockWidget({required this.myBlock , this.blockWidth , this.blockHeight });

  var myBlock;
  final blockHeight;
  final blockWidth;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[0][0],blockY: myBlock[0][1],
          blockbreack: myBlock[0][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[1][0],blockY: myBlock[1][1],
          blockbreack:  myBlock[1][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[2][0],blockY: myBlock[2][1],
          blockbreack:  myBlock[2][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[3][0],blockY: myBlock[3][1],
          blockbreack:  myBlock[3][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[4][0],blockY: myBlock[4][1],
          blockbreack:  myBlock[4][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[5][0],blockY: myBlock[5][1],
          blockbreack:  myBlock[5][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[6][0],blockY: myBlock[6][1],
          blockbreack:  myBlock[6][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[7][0],blockY: myBlock[7][1],
          blockbreack:  myBlock[7][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[8][0],blockY: myBlock[8][1],
          blockbreack:  myBlock[8][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[9][0],blockY: myBlock[9][1],
          blockbreack:  myBlock[9][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[10][0],blockY: myBlock[10][1],
          blockbreack:  myBlock[10][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[11][0],blockY: myBlock[11][1],
          blockbreack:  myBlock[11][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[12][0],blockY: myBlock[12][1],
          blockbreack:  myBlock[12][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[13][0],blockY: myBlock[13][1],
          blockbreack:  myBlock[13][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[14][0],blockY: myBlock[14][1],
          blockbreack:  myBlock[14][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[15][0],blockY: myBlock[15][1],
          blockbreack:  myBlock[15][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[16][0],blockY: myBlock[16][1],
          blockbreack:  myBlock[16][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[17][0],blockY: myBlock[17][1],
          blockbreack:  myBlock[17][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[18][0],blockY: myBlock[18][1],
          blockbreack:  myBlock[18][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[19][0],blockY: myBlock[19][1],
          blockbreack:  myBlock[19][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[20][0],blockY: myBlock[20][1],
          blockbreack:  myBlock[20][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[21][0],blockY: myBlock[21][1],
          blockbreack:  myBlock[21][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[22][0],blockY: myBlock[22][1],
          blockbreack:  myBlock[22][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[23][0],blockY: myBlock[23][1],
          blockbreack:  myBlock[23][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[24][0],blockY: myBlock[24][1],
          blockbreack:  myBlock[24][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[25][0],blockY: myBlock[25][1],
          blockbreack:  myBlock[25][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[26][0],blockY: myBlock[26][1],
          blockbreack:  myBlock[26][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[27][0],blockY: myBlock[27][1],
          blockbreack:  myBlock[27][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[28][0],blockY: myBlock[28][1],
          blockbreack:  myBlock[28][2],
        ),
        Block(blockHeight: blockHeight,
          blockWidth: blockWidth,
          blockX: myBlock[29][0],blockY: myBlock[29][1],
          blockbreack:  myBlock[29][2],
        ),
      ],
    );
  }
}
